import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  zh: {
    'nav.home': '首页',
    'nav.products': '产品中心',
    'nav.about': '关于我们',
    'nav.contact': '联系我们',
    'nav.news': '新闻动态',
    'hero.title': '重塑包装美学',
    'hero.subtitle': '温州云浠包装 - 专注3D滴胶贴纸与定制化包装解决方案',
    'hero.cta': '探索产品',
    'hero.contact': '在线咨询',
    'featured.title': '明星产品',
    'featured.subtitle': '精选云浠包装最具代表性的工艺作品',
    'stats.experience': '年行业经验',
    'stats.clients': '全球合作伙伴',
    'stats.products': '定制化产品',
    'footer.about': '温州云浠包装有限公司致力于为全球客户提供高品质、创新性的包装解决方案。',
    'footer.contact': '联系方式',
    'footer.address': '浙江省温州市龙港市印刷产业园 A 区 88 号',
    'footer.rights': '© 2026 温州云浠包装有限公司. 版权所有.',
    'common.more': '查看更多',
    'common.inquiry': '立即询价',
    'common.moq': '起订量',
    'common.price': '价格范围',
    'contact.title': '联系我们',
    'contact.subtitle': '如果您有任何疑问或定制需求，请随时与我们联系。',
    'contact.form.name': '您的姓名',
    'contact.form.email': '电子邮箱',
    'contact.form.message': '留言内容',
    'contact.form.send': '发送消息',
    'about.title': '关于云浠',
    'about.subtitle': '十年匠心，专注包装印刷艺术',
    'products.title': '产品中心',
    'products.subtitle': '我们提供多元化的包装与印刷解决方案，满足不同行业的定制化需求。从高精度的滴胶工艺到耐候性强的工业标签，每一件产品都凝聚了我们的匠心品质。',
    'products.search': '搜索产品名称或关键词...',
    'products.noFound': '未找到相关产品',
    'products.tryAdjust': '尝试调整搜索词或分类筛选',
    'products.reset': '重置所有筛选',
    'products.viewDetails': '查看详情',
    'products.custom.title': '没找到您需要的规格或款式？',
    'products.custom.desc': '作为源头工厂，我们支持 100% 深度定制。无论是特殊的材质、异形切割还是复杂的印刷工艺，我们都能为您实现。',
    'products.custom.cta': '立即开启定制咨询',
    'products.adv.sampling': '免费打样',
    'products.adv.delivery': '极速出货',
    'products.adv.moq': '小批量起订',
    'products.adv.design': '专业设计',
    'products.seo.title': '产品中心 - 温州云浠包装有限公司',
    'products.seo.desc': '浏览温州云浠包装有限公司的全系列产品，包括3D滴胶贴纸、工业不干胶标签、定制礼品包装盒等。支持小批量定制与大批量批发。',
    'cat.all': '全部',
    'cat.epoxy': '3D滴胶贴纸',
    'cat.labels': '不干胶标签',
    'cat.boxes': '定制包装盒',
    'cat.bags': '纸袋/手提袋',
    'product.retailPrice': '零售价',
    'product.factoryDirect': '厂家直供',
    'product.wholesaleTiers': '批发阶梯价格',
    'product.inquiryCta': '立即询价定制',
    'product.sampleCta': '获取免费样品',
    'product.quality': '品质保障',
    'product.shipping': '全球配送',
    'product.sampling': '极速出样',
    'product.tab.details': '详情',
    'product.tab.specs': '规格参数',
    'product.tab.process': '定制流程',
    'product.noSpecs': '暂无详细规格参数，请咨询客服获取。',
    'product.process.step1.title': '需求沟通',
    'product.process.step1.desc': '确认尺寸、材质、工艺及数量需求。',
    'product.process.step2.title': '设计打样',
    'product.process.step2.desc': '专业设计师协助排版，提供实物样品。',
    'product.process.step3.title': '批量生产',
    'product.process.step3.desc': '全自动化设备高效生产，严格质检。',
    'product.process.step4.title': '极速发货',
    'product.process.step4.desc': '专业包装加固，全球物流快速送达。',
    'product.detail.desc': '温州云浠包装出品的这款产品采用了行业领先的印刷工艺。我们注重每一个细节，从原材料的选择到最终的成品检测，都严格遵循 ISO9001 质量管理体系。',
    'contact.hero.title': '开启您的定制合作',
    'contact.hero.desc': '无论您是初创品牌还是行业巨头，我们都将为您提供最专业的包装建议与最具竞争力的报价。请填写表单或通过以下方式直接联系我们。',
    'contact.info.phone.label': '咨询热线',
    'contact.info.phone.sub': '周一至周六 8:00 - 18:00',
    'contact.info.email.label': '电子邮箱',
    'contact.info.email.sub': '我们将在 24 小时内回复您的邮件',
    'contact.info.address.label': '工厂地址',
    'contact.info.address.sub': '欢迎预约实地考察',
    'contact.form.success.title': '提交成功！',
    'contact.form.success.desc': '感谢您的咨询，我们的客户经理将在 24 小时内与您联系。',
    'contact.form.success.btn': '再次提交',
    'contact.form.name.label': '您的姓名',
    'contact.form.name.placeholder': '例如：张先生',
    'contact.form.phone.label': '联系电话',
    'contact.form.phone.placeholder': '您的手机或座机',
    'contact.form.email.label': '电子邮箱',
    'contact.form.email.placeholder': 'example@email.com',
    'contact.form.content.label': '咨询内容',
    'contact.form.content.placeholder': '请简要描述您的定制需求（如：产品类型、尺寸、数量等）',
    'contact.form.submit': '立即发送咨询',
    'contact.form.privacy': '点击发送即代表您同意我们的隐私政策',
    'contact.map.view': '在地图中查看路线',
    'contact.seo.title': '联系我们 - 温州云浠包装有限公司',
    'contact.seo.desc': '有任何关于3D滴胶贴纸、不干胶标签或定制包装的需求？欢迎随时联系温州云浠包装。我们提供免费报价与专业咨询服务。',
    'about.hero.title': '匠心制造 云浠包装',
    'about.hero.desc1': '温州云浠包装有限公司坐落于中国著名的“印刷之都”——温州龙港。自成立以来，我们始终秉承“品质第一、客户至上”的经营理念，致力于为全球客户提供最具竞争力的包装解决方案。',
    'about.hero.desc2': '我们不仅是一家工厂，更是您的品牌合作伙伴。通过持续的技术创新与设备升级，我们已经发展成为集研发、设计、生产、销售于一体的现代化包装印刷企业。',
    'about.stats.exp': '行业深耕经验',
    'about.mission.title': '我们的使命',
    'about.mission.desc': '通过卓越的包装工艺，提升客户的品牌价值，让每一件产品都能在市场上脱颖而出。',
    'about.vision.title': '我们的愿景',
    'about.vision.desc': '成为全球领先的定制化包装服务商，引领行业向绿色、智能、高效的方向持续发展。',
    'about.factory.title': '生产实力与设备',
    'about.factory.desc': '我们拥有 5000 平方米的现代化无尘车间，引进行业顶尖生产设备，确保每一道工序的精准与高效。',
    'about.equip.1.title': '海德堡印刷机',
    'about.equip.1.desc': '德国进口五色/六色印刷机，确保色彩还原度高达 99%。',
    'about.equip.2.title': '全自动滴胶线',
    'about.equip.2.desc': '高精度自动点胶设备，日产能达 10 万件，厚度均匀一致。',
    'about.equip.3.title': '智能模切系统',
    'about.equip.3.desc': 'CCD 视觉对位模切机，支持各种复杂异形切割，误差控制在 0.05mm 以内。',
    'about.cert.iso': 'ISO9001 认证',
    'about.cert.sgs': 'SGS 环保认证',
    'about.cert.factory': '源头直供',
    'about.cert.trade': '全球贸易',
    'about.history.title': '发展历程',
    'about.history.1.title': '工厂成立',
    'about.history.1.desc': '在温州龙港正式建立生产基地，专注于不干胶标签印刷。',
    'about.history.2.title': '技术升级',
    'about.history.2.desc': '引进全自动滴胶生产线，业务拓展至 3D 滴胶贴纸领域。',
    'about.history.3.title': '规模扩张',
    'about.history.3.desc': '搬迁至 5000㎡ 现代化厂房，通过 ISO9001 质量体系认证。',
    'about.history.4.title': '品牌出海',
    'about.history.4.desc': '成立国际贸易部，产品远销欧美、东南亚等 30 多个国家。',
    'about.seo.title': '关于我们 - 温州云浠包装有限公司',
    'about.seo.desc': '深入了解温州云浠包装有限公司。我们是一家拥有10年经验的专业包装制造厂商，专注于3D滴胶贴纸、不干胶标签及定制包装的研发与生产。',
    'news.hero.title': '新闻资讯',
    'news.hero.desc': '在这里，我们分享云浠包装的最新成果、行业前沿的技术洞察以及关于品牌包装的深度思考。',
    'news.readMore': '阅读全文',
    'news.nextPage': '下一页',
    'news.newsletter.title': '订阅行业简报',
    'news.newsletter.desc': '获取最新的包装趋势、技术更新及云浠包装的独家优惠信息。',
    'news.newsletter.placeholder': '您的电子邮箱地址',
    'news.newsletter.btn': '立即订阅',
    'news.cat.company': '公司动态',
    'news.cat.industry': '行业资讯',
    'news.author.center': '云浠新闻中心',
    'news.author.observer': '行业观察',
    'news.author.qc': '质检部',
    'news.seo.title': '新闻资讯 - 温州云浠包装有限公司',
    'news.seo.desc': '关注温州云浠包装的最新动态、行业趋势及包装印刷技术干货。了解我们如何通过技术创新引领包装行业发展。',
    'footer.links': '快速链接',
    'footer.admin': '管理后台',
    'footer.phone': '电话咨询',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'home.hero.badge': '专业制造商',
    'home.hero.title1': '卓越品质',
    'home.hero.title2': '定义包装未来',
    'home.hero.video': '观看工厂视频',
    'home.stats.factory': '厂房面积',
    'home.stats.capacity': '日均产能',
    'home.cats.title': '核心业务领域',
    'home.cats.all': '查看全部分类',
    'home.factory.title1': '源头工厂',
    'home.factory.title2': '全流程品质管控',
    'home.cta.title': '准备好开启您的定制包装之旅了吗？',
    'home.cta.browse': '浏览产品目录',
  },
  en: {
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.news': 'News',
    'hero.title': 'Reshaping Packaging Aesthetics',
    'hero.subtitle': 'YUNXI Packaging - Specialized in 3D Epoxy Stickers & Custom Solutions',
    'hero.cta': 'Explore Products',
    'hero.contact': 'Contact Us',
    'featured.title': 'Featured Products',
    'featured.subtitle': 'Selected representative works from Yunxi Packaging',
    'stats.experience': 'Years Experience',
    'stats.clients': 'Global Partners',
    'stats.products': 'Custom Products',
    'footer.about': 'Wenzhou Yunxi Packaging Co., Ltd. is committed to providing high-quality, innovative packaging solutions to global customers.',
    'footer.contact': 'Contact Info',
    'footer.address': 'No. 88, Area A, Printing Industrial Park, Longgang, Wenzhou, Zhejiang',
    'footer.rights': '© 2026 Wenzhou Yunxi Packaging Co., Ltd. All rights reserved.',
    'common.more': 'View More',
    'common.inquiry': 'Inquiry Now',
    'common.moq': 'MOQ',
    'common.price': 'Price Range',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Feel free to contact us for any questions or custom requirements.',
    'contact.form.name': 'Your Name',
    'contact.form.email': 'Email Address',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'about.title': 'About Yunxi',
    'about.subtitle': 'A decade of craftsmanship, focusing on the art of packaging printing',
    'products.title': 'Product Center',
    'products.subtitle': 'We provide diversified packaging and printing solutions to meet the customized needs of different industries. From high-precision epoxy processes to weather-resistant industrial labels, every product embodies our craftsmanship.',
    'products.search': 'Search product name or keywords...',
    'products.noFound': 'No products found',
    'products.tryAdjust': 'Try adjusting search terms or filters',
    'products.reset': 'Reset all filters',
    'products.viewDetails': 'View Details',
    'products.custom.title': 'Didn\'t find what you need?',
    'products.custom.desc': 'As a source factory, we support 100% deep customization. Whether it\'s special materials, irregular cutting, or complex printing, we can make it happen.',
    'products.custom.cta': 'Start Custom Inquiry',
    'products.adv.sampling': 'Free Sampling',
    'products.adv.delivery': 'Fast Delivery',
    'products.adv.moq': 'Low MOQ',
    'products.adv.design': 'Pro Design',
    'products.seo.title': 'Product Center - Wenzhou Yunxi Packaging Co., Ltd.',
    'products.seo.desc': 'Browse the full range of products from Wenzhou Yunxi Packaging Co., Ltd., including 3D epoxy stickers, industrial adhesive labels, custom gift boxes, etc. Support small batch customization and wholesale.',
    'cat.all': 'All',
    'cat.epoxy': '3D Epoxy Stickers',
    'cat.labels': 'Adhesive Labels',
    'cat.boxes': 'Custom Boxes',
    'cat.bags': 'Paper Bags',
    'product.retailPrice': 'Retail Price',
    'product.factoryDirect': 'Factory Direct',
    'product.wholesaleTiers': 'Wholesale Tiers',
    'product.inquiryCta': 'Inquiry Now',
    'product.sampleCta': 'Get Free Samples',
    'product.quality': 'Quality Assured',
    'product.shipping': 'Global Shipping',
    'product.sampling': 'Fast Sampling',
    'product.tab.details': 'Details',
    'product.tab.specs': 'Specifications',
    'product.tab.process': 'Process',
    'product.noSpecs': 'No detailed specifications available, please contact us.',
    'product.process.step1.title': 'Inquiry',
    'product.process.step1.desc': 'Confirm size, material, process, and quantity requirements.',
    'product.process.step2.title': 'Sampling',
    'product.process.step2.desc': 'Professional designers assist with layout and provide samples.',
    'product.process.step3.title': 'Production',
    'product.process.step3.desc': 'High-efficiency production with automated equipment and strict QC.',
    'product.process.step4.title': 'Delivery',
    'product.process.step4.desc': 'Professional packaging reinforcement and fast global delivery.',
    'product.detail.desc': 'This product from Wenzhou Yunxi Packaging uses industry-leading printing processes. We pay attention to every detail, from material selection to final product testing, strictly following the ISO9001 quality management system.',
    'contact.hero.title': 'Start Your Custom Cooperation',
    'contact.hero.desc': 'Whether you are a startup brand or an industry giant, we will provide you with the most professional packaging advice and the most competitive quote. Please fill out the form or contact us directly through the following methods.',
    'contact.info.phone.label': 'Hotline',
    'contact.info.phone.sub': 'Mon - Sat 8:00 - 18:00',
    'contact.info.email.label': 'Email',
    'contact.info.email.sub': 'We will reply to your email within 24 hours',
    'contact.info.address.label': 'Factory Address',
    'contact.info.address.sub': 'Welcome to book a field visit',
    'contact.form.success.title': 'Submitted Successfully!',
    'contact.form.success.desc': 'Thank you for your inquiry, our account manager will contact you within 24 hours.',
    'contact.form.success.btn': 'Submit Again',
    'contact.form.name.label': 'Your Name',
    'contact.form.name.placeholder': 'e.g. Mr. Zhang',
    'contact.form.phone.label': 'Phone Number',
    'contact.form.phone.placeholder': 'Your mobile or landline',
    'contact.form.email.label': 'Email Address',
    'contact.form.email.placeholder': 'example@email.com',
    'contact.form.content.label': 'Inquiry Content',
    'contact.form.content.placeholder': 'Please briefly describe your custom needs (e.g. product type, size, quantity, etc.)',
    'contact.form.submit': 'Send Inquiry Now',
    'contact.form.privacy': 'By clicking send, you agree to our privacy policy',
    'contact.map.view': 'View directions on map',
    'contact.seo.title': 'Contact Us - Wenzhou Yunxi Packaging Co., Ltd.',
    'contact.seo.desc': 'Any needs for 3D epoxy stickers, adhesive labels, or custom packaging? Feel free to contact Wenzhou Yunxi Packaging anytime. We provide free quotes and professional consulting services.',
    'about.hero.title': 'Craftsmanship Manufacturing Yunxi Packaging',
    'about.hero.desc1': 'Wenzhou Yunxi Packaging Co., Ltd. is located in Longgang, Wenzhou, the famous "Printing Capital of China". Since our establishment, we have always adhered to the business philosophy of "Quality First, Customer Foremost", committed to providing global customers with the most competitive packaging solutions.',
    'about.hero.desc2': 'We are not just a factory, but your brand partner. Through continuous technological innovation and equipment upgrades, we have developed into a modern packaging and printing enterprise integrating R&D, design, production, and sales.',
    'about.stats.exp': 'Years of Industry Experience',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'Through excellent packaging technology, enhance customer brand value, so that every product can stand out in the market.',
    'about.vision.title': 'Our Vision',
    'about.vision.desc': 'Become a leading global customized packaging service provider, leading the industry to continue to develop in a green, intelligent, and efficient direction.',
    'about.factory.title': 'Production Strength & Equipment',
    'about.factory.desc': 'We have a 5000 square meter modern dust-free workshop, introducing top-tier production equipment to ensure the precision and efficiency of every process.',
    'about.equip.1.title': 'Heidelberg Printing Machine',
    'about.equip.1.desc': 'German imported five-color/six-color printing machine, ensuring color restoration up to 99%.',
    'about.equip.2.title': 'Automatic Epoxy Line',
    'about.equip.2.desc': 'High-precision automatic dispensing equipment, daily capacity up to 100,000 pieces, uniform thickness.',
    'about.equip.3.title': 'Intelligent Die-cutting System',
    'about.equip.3.desc': 'CCD visual alignment die-cutting machine, supporting various complex irregular cutting, error controlled within 0.05mm.',
    'about.cert.iso': 'ISO9001 Certified',
    'about.cert.sgs': 'SGS Eco-Friendly',
    'about.cert.factory': 'Direct from Source',
    'about.cert.trade': 'Global Trade',
    'about.history.title': 'Development History',
    'about.history.1.title': 'Factory Established',
    'about.history.1.desc': 'Formally established production base in Longgang, Wenzhou, focusing on adhesive label printing.',
    'about.history.2.title': 'Technology Upgrade',
    'about.history.2.desc': 'Introduced automatic epoxy production line, expanded business to 3D epoxy sticker field.',
    'about.history.3.title': 'Scale Expansion',
    'about.history.3.desc': 'Moved to 5000㎡ modern factory, passed ISO9001 quality system certification.',
    'about.history.4.title': 'Brand Going Global',
    'about.history.4.desc': 'Established International Trade Department, products exported to more than 30 countries.',
    'about.seo.title': 'About Us - Wenzhou Yunxi Packaging Co., Ltd.',
    'about.seo.desc': 'Learn more about Wenzhou Yunxi Packaging Co., Ltd. We are a professional packaging manufacturer with 10 years of experience, focusing on the R&D and production of 3D epoxy stickers, adhesive labels, and custom packaging.',
    'news.hero.title': 'News & Insights',
    'news.hero.desc': 'Here, we share the latest achievements of Yunxi Packaging, cutting-edge industry technical insights, and deep thinking about brand packaging.',
    'news.readMore': 'Read More',
    'news.nextPage': 'Next Page',
    'news.newsletter.title': 'Subscribe to Industry Newsletter',
    'news.newsletter.desc': 'Get the latest packaging trends, technical updates, and exclusive offers from Yunxi Packaging.',
    'news.newsletter.placeholder': 'Your email address',
    'news.newsletter.btn': 'Subscribe Now',
    'news.cat.company': 'Company News',
    'news.cat.industry': 'Industry Insights',
    'news.author.center': 'Yunxi News Center',
    'news.author.observer': 'Industry Observer',
    'news.author.qc': 'QC Dept',
    'news.seo.title': 'News - Wenzhou Yunxi Packaging Co., Ltd.',
    'news.seo.desc': 'Follow the latest news, industry trends, and packaging printing technology insights from Wenzhou Yunxi Packaging. Learn how we lead the packaging industry through technical innovation.',
    'footer.links': 'Quick Links',
    'footer.admin': 'Admin',
    'footer.phone': 'Phone Inquiry',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'home.hero.badge': 'Professional Manufacturer',
    'home.hero.title1': 'Superior Quality',
    'home.hero.title2': 'Defining the Future',
    'home.hero.video': 'Watch Factory Video',
    'home.stats.factory': 'Factory Size',
    'home.stats.capacity': 'Daily Capacity',
    'home.cats.title': 'Core Business Areas',
    'home.cats.all': 'View All Categories',
    'home.factory.title1': 'Source Factory',
    'home.factory.title2': 'Full Process Quality Control',
    'home.cta.title': 'Ready to Start Your Custom Packaging Journey?',
    'home.cta.browse': 'Browse Catalog',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_lang');
    return (saved as Language) || 'zh';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_lang', lang);
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['zh']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
